# 
# This function is generated by the autotools build to "compile in"
# the local "vendor" completions, functions and configuration conf.
# It is sourced by share/config.fish, if it exists.

set __extra_completionsdir /usr/local/share/fish/vendor_completions.d
set __extra_functionsdir /usr/local/share/fish/vendor_functions.d
set __extra_confdir /usr/local/share/fish/vendor_conf.d
